FROM node:22

WORKDIR /app

# Copy the packege.json and package-lock.json
COPY . .
# Install the dependencies ci mean clean install
RUN npm ci
# Copy the source code of our app
COPY src/index.js index.js
# Expose the application port
EXPOSE 3000
# Start apllication
CMD [ "node", "index.js"]